### ISSUE TITLE
"Console assets not accessible" in AEM 6.3 after deploying composum-sling-core-package 1.8.0

### ISSUE THREAD

**Issue by kwin** [ist-dresden/composum#105]
After deploying the Composum Core Package 1.8.0 into AEM 6.3 all bundles correctly come up but still when trying to request "/bin/browser.html" I get the error "Console assets not accessible..." although the Current user is admin.
I checked both `/libs/jslibs` and `/libs/composum` and they are there in the underlying Oak and do not carry additional ACLs.

**Comment by kwin** [comment]
The reason can be found in the log
```
04.08.2017 15:05:42.352 *INFO* [0:0:0:0:0:0:0:1 [1501851942333] GET /libs/composum/nodes/console/clientlibs/base.min.css HTTP/1.1] com.composum.sling.clientlibs.service.DefaultClientlibService prepare clientlib '/libs/composum/nodes/console/clientlibs/base.min.css'...
04.08.2017 15:05:42.352 *ERROR* [0:0:0:0:0:0:0:1 [1501851942333] GET /libs/composum/nodes/console/clientlibs/base.min.css HTTP/1.1] com.adobe.granite.repository.impl.SlingRepositoryImpl Bundle com.composum.core.commons is NOT whitelisted to use SlingRepository.loginAdministrative
```

So either the loginAdministrative should be removed and instead a service resolver should be used (preferred) or alternatively the bundle needs to be whitelisted (details in https://sling.apache.org/documentation/the-sling-engine/service-authentication.html#whitelisting-bundles-for-administrative-login).

**Comment by ist-rw** [comment]
The Core package is implemented to provide a wide range of Sling and AEM versions. Therefore the necessary administrative logins are currently not transformed into service users based logins. But i think we will do this in one of the next releases.
Until then we have to whitelist the bundles - configuration added. Thanks for your help.

**Comment by ist-rw** [comment]
composum-core-1.8.1 released with a whitelist configuration embedded in the composum-core-package

**Comment by ist-rw** [comment]
Doe's this solve the problem? I would like close this issue.

**Comment by kwin** [comment]
Yes, this works now. Thanks a lot for the quick fix.
