### ISSUE TITLE
Unable to create property: name, type and value must be specified

### ISSUE THREAD

**Issue by rombert** [ist-dresden/composum#109]
I am trying out Composum 1.8.1 in the dev Sling launchpad (9-SNAPHOST). I can create nodes, edit and delete properties just fine, but trying to add a property results in an error: name, type and value must be specified

![image](https://user-images.githubusercontent.com/21237/29019446-351b9332-7b67-11e7-8254-99f7534c07cf.png)

**Comment by ist-rw** [comment]
Should be solved with [Release 1.8.2](https://github.com/ist-dresden/composum/releases/tag/composum-core-1.8.2).

**Comment by ist-rw** [comment]
Is there anything open? I would like close this issue.

**Comment by rombert** [comment]
Release 1.8.2 solves my problem ,feel free to close.
