### ISSUE TITLE
doc request - composum core update

### ISSUE THREAD

**Issue by chrismade** [ist-dresden/composum#118]
on page
https://ist-software.atlassian.net/wiki/spaces/CMP/pages/45866521/Composum+Nodes
a section might be helpful how to upgrade an existing installation of the composum core packages.
stopping and replacing each module (commons, console, jslibs etc) by jar file might be one way to go.
The existence of a package  composum-sling-core-package-1.8.2.zip suggests that update thru the package manager may work, too (maybe I'm wrong and the package only exists to add composum core to AEM).
However, trying to update composum core 1.7.0 to 1.8.2 using named package and composum package manager seems to work - the only issue is that composum-sling-package-manager-1.8.2.jar does NOT update and remains on 1.7.0 - likely because the module cannot replace itself while being actively used.
Install this missing module manually later on by "install/update" and manually deleting the V1.7.0 version of this modul seems to work.
Is there a recommended update procedure ? Or are there any no-gos which seem to work in the first place and lead to issues later on ?

**Comment by stoerr** [comment]
Right, updating the core using the package manager is bound to fail, since it replaces the package manager itself - only installing bundles works.

The page currently talks about installing bundles, only, so I assume this is obsolete and close it.
