### ISSUE TITLE
doc request - composum access to authenticated users only

### ISSUE THREAD

**Issue by chrismade** [ist-dresden/composum#119]
by default access to /bin/browser.html is open to all users, also non-authenticated anonymous -
is this necessary by design ? Or is there a way to restrict access to authenticated users only by showing a login dialog - and if so, what is the most recommended way to set this up ?

**Comment by ist-rw** [comment]
normally - in a production context - the general access for everyone should be removed; but the access to the tools can be restricted for each tool - see: https://ist-software.atlassian.net/wiki/spaces/CMP/pages/347963419/Composum+Console - we have extended the implementation and added a short documentation

**Comment by chrismade** [comment]
thanks - then we can close this - for the interim I had put a varnish in front of sling an blocked the url pattern - but this native solution is even better
