### ISSUE TITLE
[Feature] Allow saving JCR Query results 

### ISSUE THREAD

**Issue by ieugen** [ist-dresden/composum#140]
Hi, 

Composum is really handy when it comes to viewing and adding content by hand. It is also usefull for searching using SQL2 queries [1] however it does not have a way to save those queries to be used outside. 

I believe having an option to export as XML or JSON would be really great !

Regards, 
[1] https://wiki.magnolia-cms.com/display/WIKI/JCR+Query+Cheat+Sheet

**Comment by ist-rw** [comment]
There is a first working solution available as draft in the 'develop' branch (1.10.0-SNAPSHOT); see also the concept: 
https://demo.composum.com/home/console/queries.html

**Comment by ieugen** [comment]
Hi, did not try it but read the presentation. It looks really great. 
If I can get the json I can use a tool like `jq` to process the json and transform my data. 

Come to think about it, it would be cool to add a JS jq view to process the data in browser !? 

tools: https://jq.alhur.es/ 
jq finder: https://jq.alhur.es/finder/
interactive explorer: https://jq.alhur.es/jiq/

**Comment by stoerr** [comment]
A JSON and CSV download was provided for the browser, so I'm closing this. The jq view is a nice idea, but I guess this has too much overlap with the already existing SQL2 / Xpath query functionality.
