### ISSUE TITLE
Move metatype localization property files

### ISSUE THREAD

**Issue by enapps-enorman** [ist-dresden/composum#150]
Can you move the metatype localization files in a different location?  It looks like the felix.metatype is trying to parse them as xml files.

It looks related to https://issues.apache.org/jira/browse/FELIX-5700 so I would expect you would just need to update to the fixed version of the maven-scr-plugin.

For example, ERROR messages like the following are being logged in the sling log file:

22.09.2018 12:43:11.299 *ERROR* [qtp2123433131-1188] org.apache.felix.metatype fromDocuments: Error accessing document bundle://6bf42064-c134-4af2-b144-6b4b68442e19_112.0:0/OSGI-INF/metatype/com.composum.sling.clientlibs.service.ClientlibConfigurationService.properties : XML parsing exception while reading metadata: name expected (position:START_TAG <null>@7:218 in bundle://6bf42064-c134-4af2-b144-6b4b68442e19_112.0:0/OSGI-INF/metatype/com.composum.sling.clientlibs.service.ClientlibConfigurationService.properties)

**Comment by stoerr** [comment]
@ist-rw : Such .properties files are there in version 1, but not anymore in version 2. Since that seems to be just an error log, I suggest we do nothing here and close it once version 2 is released.
