### ISSUE TITLE
Direct link from resourceType etc. to component

### ISSUE THREAD

**Issue by stoerr** [ist-dresden/composum#151]
In the attributes of a node view, there are often references to other places in the JCR tree - for instance with sling:resourceType, sling:resourceSupertype, cq:template, maybe others. It would be nice to have a shortcut to directly go there. It should be easily possible to open that in another tab / window in the browser.

It might make sense to show the different locations of https://github.com/ist-dresden/composum/issues/147 here directly, too. 

A button for this could either be done for a predefined list of attribute names, or just show up on anything that "looks like a path or path fragment" (contain some slashes?) and is either a direct path in the JCR, or resolves to something using the ResourceResolver search path.

**Comment by ist-rw** [comment]
implementation done, release 2.0
