### ISSUE TITLE
Installation like described in https://ist-software.atlassian.net/wiki/spaces/CMP/pages/45866521/Composum+Nodes is outdated

### ISSUE THREAD

**Issue by kwin** [ist-dresden/composum#154]
I am trying to install Composum Nodes 1.9.2 in AEM 6.3.2.2 like described in https://ist-software.atlassian.net/wiki/spaces/CMP/pages/45866521/Composum+Nodes.

I first tried to deploy the following bundles individually via the WebConsole:
1. Commons
2. Config
3. Console
4. JSLibs

Afterwards calling `/bin/browser` lead to an empty page (delivered with a 200 status).
Then I tried to install the package https://github.com/ist-dresden/composum/releases/download/composum-nodes-1.9.2/composum-sling-core-package-1.9.2.zip via the package manager. Still the same result. 

I don't see any error in the log either except for `... GET /favicon.ico HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Resource /favicon.ico not found`.

The response body for the request to `/bin/browser` is empty. Any idea what could be wrong?

**Comment by ist-rw** [comment]
Do you use '/bin/browser' (without extension) or '/bin/browser.html'? without an extension the response is empty; the extension is necessary because the browser servlet is using the suffix as the initial path and the browser is working on top of the sling servlet engine.

**Comment by kwin** [comment]
Indeed it was the missing extension. Would it be possible to register a servlet for every extension to emit a redirect even in case `/bin/browser` has been requested?

**Comment by ist-rw** [comment]
Done. The console servlets are now supporting requests to the raw servlet path. Such a request is redirected to the same path with the right extension appended. The release 1.9.3 contains the fix and also the fix for #149, #155.
