### ISSUE TITLE
Service Graph SVG -> IMG

### ISSUE THREAD

**Issue by klcodanr** [ist-dresden/composum#183]
It would be nice to be able to download / share the service graph which would be easier if it were an image vs the current SVG. I have written up a fairly straightforward JavaScript snippet to convert the SVG into an image that the user could then save to their computer:
https://gist.github.com/klcodanr/2fbfc9b1ea369ad42b62cbe0aeb6ea09#file-svg2img-js-L1

**Comment by stoerr** [comment]
Thank you for the nice contribution! It's always nice to hear if someone uses that and even finds it important enough to write some code for it. :-) That'll go in the next core release; if you'd like you can try it in the current snapshot, too.

**Comment by stoerr** [comment]
That's in core release 11.6, so I'll close it.
