### ISSUE TITLE
Composum 2.1.0 release has link to SNAPSHOT parent

### ISSUE THREAD

**Issue by rombert** [ist-dresden/composum#217]
I tried to update the Sling Starter 12 to Composum Nodes 2.1.0, but failed because of the following error

```
[ERROR] Failed to execute goal on project org.apache.sling.starter: Could not resolve dependencies for project org.apache.sling:org.apache.sling.starter:jar:12-SNAPSHOT: Failed to collect dependencies at com.composum.nodes:composum-nodes-commons:jar:2.1.0: Failed to read artifact descriptor for com.composum.nodes:composum-nodes-commons:jar:2.1.0: Failure to find com.composum.meta.ist:parent-2-public:pom:1.3-SNAPSHOT in https://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
```

The parent dependency chain is

com.composum.nodes:composum-nodes-commons:jar:2.1.0
→ com.composum.nodes:composum-nodes:2.1.0
  → com.composum.meta.ist:parent-2-public:1.3-SNAPSHOT

The release is unfortunately not suitable for use if we only use Maven Central.

**Comment by ist-rw** [comment]
Sorry about that, release 2.1.1 should solve this problem.

**Comment by rombert** [comment]
Thanks for the quick fix! I updated the Sling Starter in https://github.com/apache/sling-org-apache-sling-starter/commit/d182d7b .
