### ISSUE TITLE
Package manager not working

### ISSUE THREAD

**Issue by royteeuwen** [ist-dresden/composum#26]
When using the latest release (1.5.0) there should be a new package manager console? It doesn't seem to appear in the /bin/browser.html top navigation. When going directly to /bin/packages.html I get following error when using Sling 8:

Error reading 'viewType' on type com.composum.sling.core.pckgmgr.view.PackageManagerBean (500)

The requested URL /bin/packages.html/ resulted in an error in /libs/composum/sling/pckgmgr/pckgmgr.jsp.

javax.el.ELException: Error reading 'viewType' on type com.composum.sling.core.pckgmgr.view.PackageManagerBean

Caused by: java.lang.NoClassDefFoundError: org/apache/jackrabbit/vault/packaging/PackagingService
	at com.composum.sling.core.pckgmgr.util.PackageUtil.createPackageManager(PackageUtil.java:62)
	at com.composum.sling.core.pckgmgr.util.PackageUtil.getResource(PackageUtil.java:81)

**Comment by ist-rw** [comment]
The package manager needs the 'Apache Jackrabbit FileVault' module. The presence of this module (of a key class of this module) ist tested during module setup. If this test fails the module is not embedded in the main navigation. it seems that this test fails. Is the FileVault available on your system?

**Comment by royteeuwen** [comment]
what do you mean by module? Is this a specific bundle that needs to be installed? Could you give me the needed maven dependency? And why isn't this a required bundle then for the package manager bundle to be installed?

**Comment by ist-rw** [comment]
The dependency is declared as 'optional' because if you don't need the package manager the Composum tool should work and not fail but without the package manager feature.
        <dependency>
            <groupId>org.apache.jackrabbit.vault</groupId>
            <artifactId>org.apache.jackrabbit.vault</artifactId>
            <version>[2.4.0,)</version>
            <scope>provided</scope>
           **<optional>true</optional>**
        </dependency>

**Comment by royteeuwen** [comment]
I understand that the composum tool should work without, but seeing as the package manager is a separate bundle that is specifically meant for the package manager, I don't see a reason why this one couldn't be dependent on it? Or will the core not work without the package manager bundle itself?

**Comment by ist-rw** [comment]
The package manager module of Composum itself is optional, yes, it mustn't be present. But if the module is bundled in a package or declared via the Sling feature configuration then in my option this check is useful and the 'optional' dependency also.

**Comment by royteeuwen** [comment]
I can't seem to find the vault dependency? 

Could not find artifact org.apache.jackrabbit.vault:org.apache.jackrabbit.vault:jar:2.4.0 in central (https://repo.maven.apache.org/maven2)


I only find it from version 3.0.0, nothing below. 
http://mvnrepository.com/artifact/org.apache.jackrabbit.vault/org.apache.jackrabbit.vault

**Comment by ist-rw** [comment]
3.0.0 is perfect, 2.4.0 is the minimum - this version is not a public version but bundled with older AEM versions

**Comment by royteeuwen** [comment]
Oke perfect it works now :)! what is the url to deploy a package it when using a maven plugin (like for crx)?

**Comment by ist-rw** [comment]
You can find an example project in 'src/test/...' with the following plugin configuration:
```
<plugin>
    <groupId>com.day.jcr.vault</groupId>
    <artifactId>content-package-maven-plugin</artifactId>
    <version>0.0.24</version>
    <extensions>true</extensions>
    <configuration>
    <failOnError>true</failOnError>
    <targetURL>http://${sling.host}:${sling.port}${sling.context}/bin/core/package.service.html</targetURL>
    <userId>admin</userId>
    <password>admin</password>
    <useProxy>false</useProxy>
    <failOnMissingEmbed>true</failOnMissingEmbed>
    </configuration>
</plugin>
```

**Comment by royteeuwen** [comment]
Cool! thanks. Last question :). Does the bundle also include installing zip files when put in the install folder on file disk? And will embedded zips / bundles also be installed?

**Comment by ist-rw** [comment]
I'm not sure, it's possible that the Jackrabbit Vault check the install folder, the Composum package manager does this not; but embedded bundles should be installed, this is a Vault feature; at least - i haven't testet this for embedded Zip files.

**Comment by royteeuwen** [comment]
K, I will give it a try then. thanks :)
