### ISSUE TITLE
Sling 9 currently not supported?

### ISSUE THREAD

**Issue by royteeuwen** [ist-dresden/composum#29]
Hey,

I am trying to use composum in the current sling launchpad 9-SNAPSHOT, but the following bundle does not seem to be satisfied anymore for the composum commons bundle:

org.apache.sling.event.jobs,version=[1.3,2) -- Cannot be resolved

Greets,
Roy

**Comment by rombert** [comment]
Should already be fixed with #27

**Comment by royteeuwen** [comment]
Hey Robert,

Ah thanks for already reporting it! Missed the 1.5.1 release ;).

Greets
Roy
