### ISSUE TITLE
SVG images are not displayed in the image frame

### ISSUE THREAD

**Issue by rombert** [ist-dresden/composum#3]
The Sling Launchpad 8 contains a Sightly repl out-of-the box and that contains an SVG image.

Navigating to http://localhost:8080/bin/browser.html/etc/clientlibs/repl/images/sightly.svg does not render the SVG image in the frame ; looking at the network tab it seems that there is no request made for it.

**Comment by mzeibig** [comment]
It looks like a browser dependent behaviour. Works fine with Chrome (45) but not in Firefox (41).
