### ISSUE TITLE
Moving a node doesn't seem to work

### ISSUE THREAD

**Issue by royteeuwen** [ist-dresden/composum#30]
I created two test folders (folder-1 and folder-2, both of type sling:Folder) and a test node (node-1 of type nt:unstructured). When being logged in as admin and trying to move node-1 from /content/folder-1 to /content/folder-2, I get following exception in the error.log:

01.05.2016 11:53:25.087 *ERROR* [0:0:0:0:0:0:0:1 [1462096405087] PUT /bin/core/node.move.json/content/folder-1/node-1 HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.NullPointerException: null
	at com.composum.sling.core.servlet.NodeServlet$MoveOperation.doIt(NodeServlet.java:756)
	at com.composum.sling.core.servlet.ServletOperationSet.doPut(ServletOperationSet.java:199)
	at com.composum.sling.core.servlet.AbstractServiceServlet.doPut(AbstractServiceServlet.java:91)
	at org.apache.sling.api.servlets.SlingAllMethodsServlet.mayService(SlingAllMethodsServlet.java:151)

**Comment by ist-rw** [comment]
reproducible in Sling-9-SNAPSHOT; works without errors in Sling-Launchpad-8

**Comment by rombert** [comment]
If you think this is a bug that appeared in the Sling 9 launchpad do tell us about it

**Comment by ist-rw** [comment]
It seems that the InputStream of a SlingRequest is now pre-read by the SlingServlet and the content is not available for direct use (throws an EOFException on access) - the transformation from JSON into a POJO based on the streams content fails.

**Comment by mzeibig** [comment]
It looks like the class `AbstractAuthenticationHandler` is consuming the `InputStream` so it is at EOF if we try to read it.

```
    @Deprecated
    public static String getAttributeOrParameter(final HttpServletRequest request, final String name,
            final String defaultValue) {
        return AuthUtil.getAttributeOrParameter(request, name, defaultValue);
    }

```

**Comment by ist-rw** [comment]
This affects potentially all change operations with or without error messages; Composum is currently not usable on Sling 9 or AEM 6.2 instances.

**Comment by mzeibig** [comment]
@rombert : It is an error in our Javascript code. I will fix it.

**Comment by mzeibig** [comment]
fixed

**Comment by rombert** [comment]
@mzeibig - thanks for confirming and also for the fix.
