### ISSUE TITLE
Getting response on failed package installation

### ISSUE THREAD

**Issue by royteeuwen** [ist-dresden/composum#32]
Is it possible to also get response when the content package installation fails for the packagemanager when using a maven plugin? I tried both the content-package-maven-plugin and also the maven-vault-plugin, but they both give success even when the package contains errors. The package gets correctly installed when it doesn't contain errors.

The tried configurations are:

                    <plugin>
                        <groupId>com.day.jcr.vault</groupId>
                        <artifactId>content-package-maven-plugin</artifactId>
                        <version>0.0.23</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>install-package</id>
                                <goals>
                                    <goal>install</goal>
                                </goals>
                                <configuration>
                                    <packageFile>${project.build.directory}/${project.build.finalName}.zip</packageFile>
                                    <targetURL>http://${sling.host}:${sling.port}/bin/core/package.service.html</targetURL>
                                    <userId>${sling.user}</userId>
                                    <password>${sling.password}</password>
                                    <useProxy>false</useProxy>
                                    <failOnError>true</failOnError>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

And

                    <plugin>
                        <groupId>com.day.jcr.vault</groupId>
                        <artifactId>maven-vault-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>install-package</id>
                                <goals>
                                    <goal>install</goal>
                                </goals>
                                <configuration>
                                    <packageFile>${project.build.directory}/${project.build.finalName}.zip</packageFile>
                                    <targetURL>http://${sling.host}:${sling.port}/bin/core/package.service.html</targetURL>
                                    <userId>${sling.user}</userId>
                                    <password>${sling.password}</password>
                                    <useProxy>false</useProxy>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

For example, when installing manually through the /bin/packages.html: 
`Caused by: org.apache.jackrabbit.vault.packaging.PackageException: javax.jcr.nodetype.ConstraintViolationException: OakConstraint0001: /apps/test[[nt:folder]]: No matching definition found for child node test with effective type [nt:unstructured]`

**Comment by ist-rw** [comment]
currently the 'OK' is sent if the install job has been started - but accepted, we have to improve this

**Comment by royteeuwen** [comment]
Cool, thanks 👍 !
