### ISSUE TITLE
Client libraries encoding may be broken if the response writer does not use UTF-8 by default

### ISSUE THREAD

**Issue by olaf-otto** [ist-dresden/composum#39]
On AEM 6.x, the composum browser fails to load because the JavaScript is only partially delivered to the client. It appears this is due to the fact that a non UTF-8 encoding is used by the response writer, resulting in a mismatch between the content-length header and the actual content length and a broken encoding (of JS and CSS alike).

**Comment by ist-rw** [comment]
thanks a lot
