### ISSUE TITLE
Create a slingfeature

### ISSUE THREAD

**Issue by rombert** [ist-dresden/composum#4]
For easier consumption it would be great if composum would be packaged as a slingfeature ( just a list of bundles in txt format ).

I've added an example of how this could be done in my fork at https://github.com/ist-dresden/composum/compare/master...rombert:slingfeature

**Comment by ist-rw** [comment]
cross ref: https://issues.apache.org/jira/browse/SLING-5292

**Comment by rombert** [comment]
Note that the SLING issue refers to deploying Composum to the Karaf launchpad, which is not part of the default Sling launchpad. Having a Composum slingfeature would make it simpler to consume it in a slingstart-based application.
