### ISSUE TITLE
Support installing content packages via the provisioning model

### ISSUE THREAD

**Issue by rombert** [ist-dresden/composum#43]
When provisioning a Sling launchpad all deployables are defined in the provisioning model ( or the bundle list, for older versions ).

It would be great if, besides allowing package installation via the web UI and the HTTP interface, composum would support installing content packages via the provisioning model. I think that support needs to be added to the OSGi installer for a different artifact type.

Adding a package via the provisioning model is done by adding a new artifact with the zip extension

    [feature name=model]
    [artifacts]
	com.example/my-content-package/0.0.1-SNAPSHOT/zip

In the [http://localhost:8080/system/console/status-osgi-installer](OSGi installer status page) you can see that the content package is not processed

    Untransformed Resources
    -----------------------
    Files:
    - 1469734419000/50, launchpad:resources/install/0/my-content-package-0.0.1-SNAPSHOT.zip

**Comment by royteeuwen** [comment]
+5 :D!

**Comment by royteeuwen** [comment]
Thats like the very last feature that I miss in the sling + composum combi to make it REALLY usefull to make a cool application :)

**Comment by mzeibig** [comment]
# Some information on how to use this **very last feature**

* add the new bundle to your `:boot` feature:

```
[feature name=:boot]

[settings]
...

[artifacts]
...
com.composum.sling.core/composum-sling-osgi-package-installer/1.6.0-SNAPSHOT
```

* add your content package and vault to your feature:

```
[feature name=composum-console]

[artifacts startLevel=20]
...
org.apache.jackrabbit.vault/org.apache.jackrabbit.vault/3.1.27-SNAPSHOT
com.composum.sling.core/maven-package-test-package/1.0.6-SNAPSHOT/zip
```

* build your launchpad

* start the launchpad

* the results of the installation (logs) will be visible in the package manager tab

**Comment by rombert** [comment]
Great news, thanks for the implementation!

**Comment by royteeuwen** [comment]
Very nice, going to try it out ;)!

**Comment by ist-rw** [comment]
implementation done
