### ISSUE TITLE
Where to find missing bundle dependencies?

### ISSUE THREAD

**Issue by hrj** [ist-dresden/composum#44]
Hi,

I am very new to Sling, OSGI. Composum sounded interesting, but when I install the bundle, I see this error in `/system/console/bundles`:

```
org.apache.commons.lang3,version=[3.0,4) -- Cannot be resolved
```

How do I resolve this? Do I need to compile this (and other such dependencies) myself or is there a standard repository that everyone uses?

thanks!

**Comment by rombert** [comment]
Try downloading the latest version from http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.apache.commons%22%20AND%20a%3A%22commons-lang3%22 .

**Comment by hrj** [comment]
@rombert Thanks, that worked!

I was afraid that I will have to manually download many such jars from maven, but it looks like that is the only jar that needs to be downloaded.

I have been playing with composum for sometime now and it looks awesome!
