### ISSUE TITLE
Add version 0.0.24 to content-package-maven-plugin in /corepckg

### ISSUE THREAD

**Issue by ksurendra** [ist-dresden/composum#58]
Can you add the version "0.0.24" to "content-package-maven-plugin" to https://github.com/ist-dresden/composum/blob/master/sling/core/corepckg/pom.xml

As of now it is listed as:
```xml
    <plugin>
       <groupId>com.day.jcr.vault</groupId>
       <artifactId>content-package-maven-plugin</artifactId>
       <extensions>true</extensions>
```

To be modified as..
```xml
    <plugin>
       <groupId>com.day.jcr.vault</groupId>
       <artifactId>content-package-maven-plugin</artifactId>
       <version>0.0.24</version>
       <extensions>true</extensions>
```

without the version, i'm not able to build the package. I'm using Maven 3.3.9

**Comment by royteeuwen** [comment]
I think sling is releasing/released a content package plugin, maybe that can be used instead? They also released an osgi content package installer if i'm not mistaken, so u can remove/deprecate the existing implementation

**Comment by ksurendra** [comment]
I'm not sure, have to check Apache Sling. As an interim solution, after i changed my <local-user>/.m2/settings.xml file to the on listed here 
https://helpx.adobe.com/experience-manager/using/creating-custom-aem-workflow-steps.html
the issue is resolved. This is more of telling maven where to pick the dependency file.

The package is moved to https://repo.adobe.com/nexus/content/groups/public/com/day/jcr/vault/content-package-maven-plugin/ from https://repo.maven.apache.org/maven2

**Comment by rombert** [comment]
> they also released an osgi content package installer if i'm not mistaken, so u can remove/deprecate the existing implementation

https://github.com/apache/sling/tree/trunk/installer/factories/packages

It's there but not yet released. If "someone" could give it a spin in composum _and_ the maintainers would be willing to switch to that implementation I can create a first release.
