### ISSUE TITLE
Inline edit for date fields shows incorrect value

### ISSUE THREAD

**Issue by rombert** [ist-dresden/composum#6]
If I edit a field, the date displayed as a label and the date displayed for editing are not the same.
![composum-edit-date-before](https://cloud.githubusercontent.com/assets/21237/10366161/365b3bda-6dd1-11e5-95d8-b475a7a729ae.png)
![composum-edit-date-after](https://cloud.githubusercontent.com/assets/21237/10366162/3834fd92-6dd1-11e5-943d-5b2797462c69.png)

**Comment by mzeibig** [comment]
The select options are rounded to multiples of '5' to minimise the options available. Indeed a better edit control is needed to edit. As a quick solution one can click at the property name to open a dedicated dialog to edit the value more precise.

**Comment by rombert** [comment]
Thanks for indicating the quick solution.

**Comment by ist-rw** [comment]
solved with release 1.2.0
