### ISSUE TITLE
Compilation of composum source(1.7.0) and master fails

### ISSUE THREAD

**Issue by rsingareddy** [ist-dresden/composum#61]
I have checked out trunk and executed mvn  clean install giving maven dependency errors.

[WARNING] The POM for com.day.jcr.vault:content-package-maven-plugin:jar:0.0.24 is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.0.24 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.0.24 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @
[ERROR] Unknown packaging: content-package @ com.composum.sling.core:composum-sling-core-package:[unknown-version], D:\code\framework\research_code\composum-release-1.7.0\sling\core\corepckg\pom.xml, line 13, column 16
[WARNING] 'build.plugins.plugin.version' for org.apache.felix:maven-bundle-plugin is missing. @ line 21, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.felix:maven-bundle-plugin is missing. @ line 21, column 21
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.composum.sling.core:composum-sling-core-package:1.7.0 (D:\composum-release-1.7.0\sling\core\corepckg\pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.0.24 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.0.24 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR]     Unknown packaging: content-package @ com.composum.sling.core:composum-sling-core-package:[unknown-version], D:\composum-release-1.7.0\sling\core\corepckg\pom.xml, line 13, column 16

**Comment by ist-rw** [comment]
Unfortunately the content package Maven plugin referenced here ist not available in a general public maven repository. The plugin is available in the Adobe public repository:
https://repo.adobe.com/nexus/content/groups/public/com/day/jcr/vault/content-package-maven-plugin/0.0.24
I use a profile 'adobe' like this:
----
        <profile>
            <id>adobe</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <releaseRepository-Id>adobe-public-releases</releaseRepository-Id>
                <releaseRepository-Name>Adobe Public Releases</releaseRepository-Name>
                <releaseRepository-URL>https://repo.adobe.com/nexus/content/groups/public</releaseRepository-URL>
            </properties>
            <repositories>
                <repository>
                    <id>adobe-public-releases</id>
                    <name>Adobe Public Repository</name>
                    <url>https://repo.adobe.com/nexus/content/groups/public</url>
                    <releases>
                        <enabled>true</enabled>
                        <updatePolicy>never</updatePolicy>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>adobe-public-releases</id>
                    <name>Adobe Public Repository</name>
                    <url>https://repo.adobe.com/nexus/content/groups/public</url>
                    <releases>
                        <enabled>true</enabled>
                        <updatePolicy>never</updatePolicy>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </pluginRepository>
            </pluginRepositories>
        </profile>
----
This is declared in my local Maven settings.
