### ISSUE TITLE
Felix console can get stuck in a broken state.

### ISSUE THREAD

**Issue by jglogan** [ist-dresden/composum#62]
How to reproduce:

1. Start Sling with a fresh repo.
2. Install a custom bundle.
3. In the composum Felix console, view the details for a component from the custom bundle.
4. Stop Sling, remove the repository, and start with a fresh repo.
5. Navigate to the Felix console.

Expected result: The default Felix console page.
Actual result:
```
HTTP ERROR: 404

Problem accessing /system/console/components/{id}. Reason:

    Not Found
```

The problem appears to be that the last viewed object is stored in browser local storage, and there's no error handling for the case where that object doesn't exist anymore.  The code that performs the lookup is in console.js:

console.js, console.profile.get():

 ```
                if (!object) {
                    var item = localStorage.getItem('composum.core.' + aspect);
                    if (item) {
                        object = JSON.parse(item);
                        console.profile.aspects[aspect] = object;
                    }
                }
```

**Comment by ist-rw** [comment]
#63 - pull request to fix this issue merged to the 'develop' branch

**Comment by ist-rw** [comment]
The fix is also available in the 'releases/1.x/v1.7' bugfix branch.
