### ISSUE TITLE
Composum should not install anything with an empty filter.xml file

### ISSUE THREAD

**Issue by schaefa** [ist-dresden/composum#67]
I ran into a few problems with my project where I changes were not updated in Sling 9 after deployment them through Composum.

It turned out that I mistakenly added META-INF folder to jcr_root rather than its parent and so META-INF that was added to the ZIP file was blank:

&lt;?xml version="1.0" encoding="UTF-8"?>
&lt;workspaceFilter version="1.0" />

It did install my JCR nodes but failed to remove them during uninstall. With that updates would fail to deploy and I could not manually uninstall the package in the package manager.

[ui.apps.example-1.0.0-SNAPSHOT.zip](https://github.com/ist-dresden/composum/files/859702/ui.apps.example-1.0.0-SNAPSHOT.zip)

This might be an VLT issue but it would be helpful if Composum could check to avoid inconsistency between install and uninstall.

**Comment by stoerr** [comment]
I'm closing this, since the installation / uninstallation process is triggered but not performed by the Composum package manager, and this is rather old, too.
