### ISSUE TITLE
Package Uploading is not respecting "force" and always forces an upload

### ISSUE THREAD

**Issue by schaefa** [ist-dresden/composum#73]
Based on CRX Package Manager forcing an upload means that it will replace an already uploaded package and it not forced then the upload will fail.

As far as I understand the code the force tag is actually migrating to Package Zip File strict which is does seem wrong.

Anyhow it would be nice if Composum could act like CRX Package Manager or otherwise use a different name.

**Comment by ist-rw** [comment]
fixed and merged into 'develop' and 'master'
