### ISSUE TITLE
How to restrict user/group access to the Composum Nodes browser?

### ISSUE THREAD

**Issue by jglogan** [ist-dresden/composum#83]
What's the recommended way to limit Composum browser access to a set of users/groups?  For the Felix console there are the user and groups OSGI config values for org.apache.sling.extensions.webconsolesecurityprovider.internal.SlingWebConsoleSecurityProvider, but I didn't see anything like this for Composum.

Thank you for any help you can provide!

**Comment by ist-rw** [comment]
The User Manager implementation should restrict the access to the users and groups. The Composum Console contains a user interface to the UserManager and has no features to control the access to the entities provided by the used user manager. But the default JCR-based implementation can be restricted using the ACLs of the repository. You should group your groups and users using appropriate intermediate paths and restrict the access to this paths by ACLs analogous to restrictions to other content paths. The ACLs itself can be edited using the Browser of the Composum Console. I've tested this and it works fine.

**Comment by jglogan** [comment]
Using the JCR-based access control on the browser paths seemed like a reasonable approach to me, but I wanted to make sure that there wasn't some other way that was deemed a better practice.

Thank you very much, Ralf!  That answers my question.
